[project]
name = "phylodata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
phylodata = "phylodata.main:main"
