[project]
name = "phylodata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "msgspec>=0.19.0",
    "nicegui>=2.20.0",
]

[project.scripts]
phylodata = "phylodata.main:main"

[dependency-groups]
dev = [
    "ruff>=0.12.0",
]
